'use client';
import {useEffect,useRef,useState} from 'react';
import {Search,Mic,Plus,Home,Settings,MapPin,ChevronRight,ArrowUpRight,Clock,Check,ShieldCheck,Box,Camera,Trash2,Download,Keyboard,MoveRight,X,CheckCircle2,Lock,HelpCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Switch} from '@/components/ui/switch';
import {Memory,parseMemory,searchMemories,emoji,examples,title} from '@/lib/memory';
import {text as copyText} from '@/lib/i18n';
import {StructuredMemoryForm} from '@/components/structured-memory-form';
import {LocationManager} from '@/components/location-manager';
const placeholders={en:['Where are my keys?','Where did I put my passport?','Where’s my charger?','Where are my headphones?'],no:['Hvor er nøklene mine?','Hvor la jeg passet mitt?','Hvor er laderen min?','Hvor er hodetelefonene mine?']};
function Brand({small=false,onHome}:{small?:boolean;onHome:()=>void}){return <button type="button" className={'brand '+(small?'small':'')} onClick={onHome} aria-label="Go to home"><div className="brand-icon"><Box size={25}/><MapPin size={17}/></div><span>Where Did<br/>I Put That<span className="green">?</span></span></button>}
function ago(date:string,language:'no'|'en'='no'){const days=Math.floor((Date.now()-new Date(date).getTime())/86400000);return days<1?(language==='no'?'i dag':'today'):days===1?(language==='no'?'i går':'yesterday'):new Date(date).toLocaleDateString(language==='no'?'nb-NO':'en-US',{month:'short',day:'numeric'});}
export default function MemoryApp(){
 const [items,setItems]=useState<Memory[]>([]),[loaded,setLoaded]=useState(false),[demo,setDemo]=useState(false),[auth,setAuth]=useState(false),[email,setEmail]=useState(''),[displayName,setDisplayName]=useState(''),[query,setQuery]=useState(''),[searched,setSearched]=useState(false),[filter,setFilter]=useState('Alle minner'),[view,setView]=useState('home'),[modal,setModal]=useState(''),[selected,setSelected]=useState<Memory|null>(null),[text,setText]=useState(''),[draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[listening,setListening]=useState(false),[source,setSource]=useState('typed'),[onboarding,setOnboarding]=useState(0),[firstItem,setFirstItem]=useState('Keys'),[notify,setNotify]=useState(false),[confirm,setConfirm]=useState(''),[photo,setPhoto]=useState<File|null>(null),[placeIndex,setPlaceIndex]=useState(0),[language,setLanguage]=useState<'en'|'no'>('en'),[locations,setLocations]=useState<any[]>([]),[profileOpen,setProfileOpen]=useState(false);
 const inputRef=useRef<HTMLInputElement>(null);const recognitionRef=useRef<any>(null);
 async function load(){try{const r=await fetch('/api/memories');const d:any=await r.json();if(r.status===401){setAuth(false);setLoaded(true);return;}if(!r.ok)throw Error(d.error);setAuth(true);setEmail(d.user.email);setDisplayName(d.user.name||d.user.email?.split('@')[0]||'');setNotify(d.notifications==='on');const location=(id:string):string[]=>{const path:string[]=[];const visited=new Set();let current=id;while(current&&!visited.has(current)){visited.add(current);const l=d.locations.find((l:any)=>l.id===current);if(!l)break;path.unshift(l.name);current=l.parent_location_id;}return path;};setLocations(d.locations||[]);setItems(d.items.map((i:any)=>({...i,saved_latitude:i.saved_latitude==null?undefined:Number(i.saved_latitude),saved_longitude:i.saved_longitude==null?undefined:Number(i.saved_longitude),location:location(i.current_location_id),history:d.history.filter((h:any)=>h.item_id===i.id).map((h:any)=>({...h,location:location(h.location_id)}))})));setLoaded(true);}catch(e:any){setError(e.message);setLoaded(true);}}
 useEffect(()=>{void Promise.resolve().then(()=>{void load();const saved=window.localStorage.getItem('where-did-i-put-that-language');const detected=(navigator.language||'').toLowerCase().startsWith('nb')||(navigator.language||'').toLowerCase().startsWith('no')?'no':'en';setLanguage((saved==='no'||saved==='en')?saved:detected);});const t=setInterval(()=>setPlaceIndex(i=>(i+1)%4),4500);return()=>{clearInterval(t);recognitionRef.current?.abort();};},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t);},[notice]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const abort=new AbortController();Promise.resolve(ctx.registerTool({name:'search_memories',description:'Search your saved belongings and show all matching locations.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(p:any)=>{if(typeof p.query!=='string'||!p.query.trim())throw Error('A search query is required');setQuery(p.query);setSearched(true);setView('home');return searchMemories(items,p.query).map(i=>({name:i.name,location:i.location}));}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort();},[items]);
 const visible=demo?examples:items;const matches=searched?searchMemories(visible,query):[];const rooms=[...new Set(visible.map(i=>i.location[0]))];const recentLocations=items.filter(i=>i.location.length&&i.location[0]!=='Usortert'&&i.location[0]!=='Unsorted').map(i=>i.location);const fixedAddress=(path:string[])=>locations.find(l=>!l.parent_location_id&&l.name===path[0])?.address as string|undefined;const shown=visible.filter(i=>filter==='Alle minner'||i.location[0]===filter);
 function openEdit(item:Memory){setOnboarding(0);setSelected(item);setText('');setDraft(null);setPhoto(null);setError('');setSource('manual edit');setModal('edit');}
 function openAdd(item?:Memory){setOnboarding(0);setSelected(item??null);setText('');setDraft(null);setPhoto(null);setError('');setSource('typed');setModal(item?'move':'add');}
 function search(q=query){setQuery(q);setSearched(true);setView('home');setFilter('Alle minner');}
 function voice(target:'search'|'remember'){const API=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!API){setError('Tale støttes ikke i denne nettleseren. Du kan skrive inn minnet nedenfor.');return;}if(listening){recognitionRef.current?.stop();return;}const r=new API();recognitionRef.current=r;r.lang=language==='no'?'nb-NO':'en-US';r.interimResults=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=(e:any)=>{setListening(false);setError(e.error==='not-allowed'?'Tillat mikrofontilgang, eller skriv i stedet.':'I didn’t catch that. Prøv igjen or type it.');};r.onresult=(e:any)=>{const result=e.results[0][0].transcript;if(target==='search')search(result);else{setText(result);setSource('voice');}setListening(false);};try{r.start();}catch{setError('Kunne ikke starte mikrofonen. Prøv å skrive i stedet.');}}
 function extract(){setError('');const forced=modal==='move'?selected?.name:onboarding===3&&firstItem!=='item'?firstItem:undefined;const d=parseMemory(text,forced);if(!d){const raw=text.trim();if(onboarding===3&&firstItem==='item'&&raw&&!/\b(in|inside|at|on|under|i|på|ved|under)\b/i.test(raw)){setFirstItem(title(raw));setText('');setError(language==='no'?'Hvor ligger den? Skriv for eksempel «i kjøkkenskuffen».':'Hvor er den? Skriv for eksempel «i kjøkkenskuffen».');return;}setError(language==='no'?'Hvor skal jeg lete? Skriv for eksempel «nøklene er i kjøkkenskuffen».':'Hvor skal jeg lete? Prøv «Nøklene er i kjøkkenskuffen».');return;}setDraft(d);}
 async function mutate(payload:any){const r=await fetch('/api/memories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d:any=await r.json();if(!r.ok)throw Error(d.error||'That didn’t work. Please try again.');return d;}
 async function save(){if(!draft)return;setBusy(true);setError('');try{let key;if(photo){const f=new FormData();f.append('photo',photo);const r=await fetch('/api/photo',{method:'POST',body:f});const d:any=await r.json();if(!r.ok)throw Error(d.error);key=d.key;}await mutate({...draft,id:modal==='move'||modal==='edit'?selected?.id:undefined,temporaryUntil:draft.temporaryUntil,source,photo:key,language,preserveLocationPin:modal==='edit'});await load();setDemo(false);setSearched(false);setDraft(null);setText('');if(onboarding===3){setOnboarding(4);}else{setModal('');setNotice(language==='no'?'Det er notert, jeg husker det for deg 👌':'Got it. I’ll remember that. 👌');}}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{await mutate({action:confirm==='item'?'delete':confirm,id:selected?.id});await load();setModal('');setSelected(null);setConfirm('');setNotice(confirm==='account'?(language==='no'?'Appkonto og minner ble slettet.':'Your app account and memories have been deleted.'):(language==='no'?'Minnene ble slettet.':'Your memories have been deleted.'));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify(items,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='my-memories.json';a.click();URL.revokeObjectURL(url);}
 const remembering=<><button className={'voice-button '+(listening?'listening':'')} onClick={()=>voice('remember')}><Mic size={25}/>{listening?(language==='no'?'Jeg lytter…':'I’m listening…'):copyText(language,'tellMe')}</button><div className="or">{copyText(language,'typeHere')}</div><textarea value={text} onChange={e=>{setText(e.target.value);setSource('typed');}} placeholder={modal==='move'?copyText(language,'exampleMove'):copyText(language,'examplePassport')} autoFocus/><div className="input-tip"><HelpCircle size={14}/>{copyText(language,'help')}</div>{error&&<div role="alert" className="error">{error}</div>}<button className="primary full" onClick={extract} disabled={!text.trim()}>{copyText(language,'rememberStarts')} <Check size={17}/></button></>;
 const confirmation=draft&&<><div className="confirmation-card"><span className="item-emoji big">{draft.icon||emoji(draft.name)}</span><h2>{draft.name}</h2><p><MapPin size={16}/>{draft.location.join(' → ')}</p>{draft.temporaryUntil&&<small><Clock size={14}/>Midlertidig til {draft.temporaryUntil}</small>}</div><p className="center muted">{language==='no'?'Ser dette riktig ut? Jeg husker akkurat dette.':'Does this look right? I’ll remember exactly this.'}</p><label className="attach"><Camera size={18}/>{photo?photo.name:(language==='no'?'Legg til bilde (valgfritt)':'Add photo (optional)')}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]??null)}/></label>{error&&<p role="alert" className="error">{error}</p>}<div className="button-row"><button className="secondary" onClick={()=>setDraft(null)}>{language==='no'?'Rediger':'Edit'}</button><button className="primary" disabled={busy} onClick={save}>{busy?(language==='no'?'Husker…':'Remembering…'):(language==='no'?'Husk det':'Remember it')}<Check size={17}/></button></div></>;
 return <div className="app-shell"><aside className="sidebar"><Brand onHome={()=>{setView('home');setSearched(false);setModal('');}}/><div className="nav-label">{language==='no'?'DIN LILLE HUKOMMELSESBANK':'YOUR LITTLE MEMORY BANK'}</div><nav><button className={view==='home'?'active':''} onClick={()=>{setView('home');setSearched(false);}}><Home size={20}/>{language==='no'?'Hjem':'Home'}</button><button onClick={()=>openAdd()}><Plus size={20}/>{language==='no'?'Husk noe':'Remember something'}</button><button className={view==='settings'?'active':''} onClick={()=>setView('settings')}><Settings size={20}/>{language==='no'?'Innstillinger':'Settings'}</button></nav><div className="sidebar-bottom"><div className="privacy-note"><ShieldCheck size={20}/><div>{language==='no'?'Bare mellom oss.':'Just between us.'}<br/><span>{language==='no'?'Minnene er dine.':'Your memories are yours.'}</span></div></div><button className="profile" onClick={()=>setProfileOpen(v=>!v)}><span className="avatar">{auth?email[0]?.toUpperCase():'Y'}</span><span>{language==='no'?'Ditt personlige område':'Your personal space'}<small>{auth?(language==='no'?'Privat og sikkert':'Private and secure'):(language==='no'?'Finn deg til rette':'Make yourself at home')}</small></span><ChevronRight size={16}/></button>{profileOpen&&<div className="profile-menu"><strong>{displayName||'Account'}<small>{email}</small></strong><button onClick={()=>{const v=language==='no'?'en':'no';setLanguage(v);window.localStorage.setItem('where-did-i-put-that-language',v);setProfileOpen(false);}}>{language==='no'?'English':'Norsk'}<ChevronRight size={15}/></button><button onClick={()=>{setView('settings');setProfileOpen(false);}} >{language==='no'?'Innstillinger':'Settings'}<Settings size={15}/></button>{auth?<a href="/cdn-cgi/access/logout" target="_top" >{language==='no'?'Logg ut':'Sign out'}</a>:<button type="button" onClick={()=>window.location.assign('/')}>{language==='no'?'Logg inn':'Sign in'}</button>}</div>}</div></aside>
 <div className="main-wrap"><header className="topbar"><span className="breadcrumb"><button className="breadcrumb-home" onClick={()=>{setView('home');setSearched(false);setModal('');}}><Home size={15}/>{language==='no'?'Hjemmet ditt':'Your home'}</button><span>/</span>{view==='home'?(language==='no'?'Hukommelsesbank':'Memory bank'):(language==='no'?'Innstillinger':'Settings')}</span><div className="topbar-right"><span><Lock size={13}/>{language==='no'?'Privat med vilje':'Private by design'}</span><button className="avatar" aria-label="Open profile menu" onClick={()=>setProfileOpen(v=>!v)}>{auth?email[0]?.toUpperCase():'Y'}</button>{profileOpen&&<div className="profile-menu top-profile-menu"><strong>{displayName||'Account'}<small>{email}</small></strong><button onClick={()=>{const v=language==='no'?'en':'no';setLanguage(v);window.localStorage.setItem('where-did-i-put-that-language',v);setProfileOpen(false);}}>{language==='no'?'English':'Norsk'}<ChevronRight size={15}/></button><button onClick={()=>{setView('settings');setProfileOpen(false);}} >{language==='no'?'Innstillinger':'Settings'}<Settings size={15}/></button>{auth?<a href="/cdn-cgi/access/logout" target="_top" >{language==='no'?'Logg ut':'Sign out'}</a>:<button type="button" onClick={()=>window.location.assign('/')}>{language==='no'?'Logg inn':'Sign in'}</button>}</div>}</div><div className="mobile-brand"><Brand small onHome={()=>{setView('home');setSearched(false);setModal('');}}/></div></header>
 <main>{view==='home'?<><section className="intro"><div className="eyebrow"><span/>{language==='no'?'LITT MINDRE «HVOR ER DEN?»':'LESS “WHERE DID I PUT IT?”'}</div><h1>{language==='no'?'Hjemmet ditt':'Your house'}<br className="mobile-break"/> {language==='no'?'husker':'remembers'}<span className="green">.</span></h1><p>{language==='no'?'Du har nok å tenke på.':'You’ve got enough on your mind.'}<br className="mobile-break"/> {language==='no'?'Vi husker de små tingene.':'Let us keep track of the little things.'}</p></section>
 <section className={'search-panel '+(searched?'expanded':'')}><form onSubmit={e=>{e.preventDefault();search();}}><Search size={25}/><div className="search-input"><label htmlFor="search">{language==='no'?'Hva leter du etter?':'What are you looking for?'}</label><input id="search" ref={inputRef} value={query} onChange={e=>{setQuery(e.target.value);if(!e.target.value)setSearched(false);}} placeholder={placeholders[language][placeIndex]}/></div>{query&&<button type="button" className="icon-button clear" aria-label="Clear search" onClick={()=>{setQuery('');setSearched(false);}}><X size={17}/></button>}<button type="button" className={'mic '+(listening?'listening':'')} aria-label="Search by voice" onClick={()=>voice('search')}><Mic size={21}/></button><button className="search-submit" type="submit">{language==='no'?'Finn':'Find it'}</button></form><div className="search-footer"><span><Mic size={13}/>{listening?(language==='no'?'Jeg lytter…':'I’m listening…'):(language==='no'?'Spør naturlig. Skriv eller si det.':'Ask naturally. Type it or say it.')}</span><span className="keyboard-hint"><Keyboard size={13}/>{language==='no'?'Trykk Enter for å finne':'Press Enter to search'}</span></div></section>
 {error&&!modal&&<div role="alert" className="error">{error}<button onClick={()=>{setError('');load();}}>Prøv igjen</button></div>}
 {searched?<section className="result-section"><div className="section-head"><h2>{matches.length===1?(language==='no'?'Jeg fant den. 👀':'I found it. 👀'):matches.length>1?(language==='no'?`Jeg husker ${matches.length} av disse. 👀`:`I remember ${matches.length} of those. 👀`):(language==='no'?'Hmm … den husker jeg ikke. 🤔':'Hmm… I don’t remember that one. 🤔')}</h2><button className="text-button" onClick={()=>{setSearched(false);setQuery('');}}>{language==='no'?'Tilbake til minner':'Back to memories'}</button></div>{matches.length>1&&<p className="muted">{language==='no'?'Hvilken leter du etter?':'Which one are you looking for?'}</p>}{matches.length===0?<div className="unknown"><Box size={35}/><h3>{language==='no'?'Vil du lære meg det?':'Would you like me to remember it?'}</h3><p>{language==='no'?'Fortell meg hvor den er, så husker jeg det neste gang.':'Tell me where it is, and I’ll remember next time.'}</p><button className="primary" onClick={()=>openAdd()}>{language==='no'?'Husk det':'Remember it'} <Plus size={16}/></button><button className="text-button" onClick={()=>{setSearched(false);inputRef.current?.focus();}}>{language==='no'?'Prøv igjen':'Try again'}</button></div>:<div className="results">{matches.map(i=><article className="result-card" key={i.id}><div className="result-top"><span className="item-emoji big">{i.icon||emoji(i.name)}</span><span className="found-label"><CheckCircle2 size={15}/>{language==='no'?'Husket':'Remembered'}</span></div><h2>{i.name}</h2><div className="result-location"><MapPin size={20}/>{i.location.join(' → ')}</div>{fixedAddress(i.location)&&<a className="map-link" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(fixedAddress(i.location)!)} target="_blank" rel="noreferrer">{language==='no'?'Åpne sted i kart':'View place on map'}</a>}{i.temporary_until&&<p className="temporary"><Clock size={15}/>Midlertidig til {i.temporary_until}</p>}<p className="muted">{language==='no'?'Sist husket':'Last saved'} {ago(i.updated_at,language)}.<br/>{copyText(language,'lastTold')}</p><div className="button-row"><button className="primary" onClick={()=>{if(demo){setNotice('This is a sample. Save your first memory to make it yours.');return;}openAdd(i);}}>Flytt den <MoveRight size={17}/></button><button className="secondary" onClick={()=>{setSelected(i);setModal('history');}}>Se historikk</button></div></article>)}</div>}</section>:<>
 {!items.length&&!demo&&loaded&&<section className="welcome-strip"><div className="welcome-symbol"><Box size={25}/></div><div><h3>{language==='no'?'La tingene dine få en hukommelse.':'Let your belongings have a memory.'}</h3><p>{language==='no'?'Start med det du alltid leter etter.':'Start with what you always look for.'}</p></div><button className="primary" onClick={()=>{setOnboarding(1);setModal('onboarding');setDraft(null);setError('');}}>{language==='no'?'Kom i gang':'Get started'}<Plus size={16}/></button></section>}
 <section className="memories"><div className="section-head"><div><h2>{language==='no'?'Nylige minner':'Recent memories'} <span className="count">{visible.length}</span></h2><p>{language==='no'?'De små tingene, akkurat der du la dem.':'The little things, right where you left them.'}</p></div><button className="text-button desktop-add" onClick={()=>openAdd()}><Plus size={17}/>{language==='no'?'Husk noe':'Remember something'}</button></div><div className="filters">{['Alle minner',...rooms].map(f=><button key={f} className={f===filter?'selected':''} onClick={()=>setFilter(f)}>{f==='Alle minner'?<Box size={14}/>:<Home size={14}/>} {f==='Alle minner'?(language==='no'?'Alle minner':'All memories'):f}</button>)}</div>
 {demo&&<div className="demo-note">{language==='no'?'Eksempelminner som viser hvordan appen fungerer.':'Sample memories to show how the app works.'}<button onClick={()=>{setDemo(false);setFilter('Alle minner');}}>{language==='no'?'Skjul eksempler':'Hide examples'}</button></div>}
 {!loaded?<div className="empty-card"><p>Åpner hukommelsesbanken…</p></div>:shown.length?<div className="memory-grid">{shown.map(i=><button key={i.id} className="memory-card" onClick={()=>{setSelected(i);setModal('detail');}}><div className="card-top"><span className={'item-emoji '+((i.icon||emoji(i.name))==='📕'?'peach':(i.icon||emoji(i.name))==='🎧'?'lavender':'')}>{i.icon||emoji(i.name)}</span><ArrowUpRight size={18}/></div><h3>{i.name}</h3><div className="location"><MapPin size={14}/>{i.location.map((l,index)=><span key={index}>{index>0&&<ChevronRight size={12}/>} {l}</span>)}</div>{i.temporary_until&&<div className="temporary"><Clock size={12}/>Til {i.temporary_until}</div>}<div className="card-bottom"><span>{language==='no'?'Husket':'Saved'} {ago(i.updated_at,language)}</span><span className="remembered-dot"/></div></button>)}<button className="add-card" onClick={()=>openAdd()}><span><Plus size={24}/></span><h3>{language==='no'?'Én ting mindre å glemme.':'One less thing to forget.'}</h3><p>{language==='no'?'Husk noe':'Remember something'}</p></button></div>:<div className="empty-card"><div className="empty-icon"><Box size={31}/></div><h3>{language==='no'?'Ingenting her ennå.':'Nothing here yet.'}</h3><p>{language==='no'?'La tingene dine få en bedre hukommelse.':'Give your things a better memory.'}</p><button className="primary" onClick={()=>openAdd()}><Plus size={17}/>Husk noe</button><button className="text-button" onClick={()=>{setDemo(true);setFilter('Alle minner');}}>{language==='no'?'Se noen eksempler':'See a few examples'} <ArrowUpRight size={15}/></button></div>}
 </section><section className="gentle-tip"><div className="tip-icon"><Mic size={20}/></div><div><h3>En tanke. En setning. Huskes.</h3><p>“Jeg la passet mitt i den øverste skuffen på soverommet.”</p></div><button aria-label="Try remembering by voice" onClick={()=>{openAdd();setTimeout(()=>voice('remember'),200);}}><ArrowUpRight size={21}/></button></section></>}
 <footer><span><ShieldCheck size={14}/>{language==='no'?'Dine ting. Dine minner. Alltid privat.':'Your things. Your memories. Always private.'}</span><span>{language==='no'?'Litt mer ro i hverdagen.':'A little more peace of mind.'}</span></footer>
 </>:<section className="settings">
    <div className="eyebrow">{language==='no'?'DITT PERSONLIGE OMRÅDE':'YOUR PERSONAL SPACE'}</div>
    <h1>{language==='no'?'Innstillinger':'Settings'}</h1>
    <p className="muted">{language==='no'?'Du bestemmer hva vi skal huske.':'You choose what we remember.'}</p>
    <div className="settings-card locations-card">
      <LocationManager locations={locations} language={language} onMutate={mutate} onChanged={load}/>
    </div>
    <details className="settings-card compact-settings">
      <summary>{language==='no'?'Midlertidige påminnelser':'Temporary reminders'}</summary>
      <div className="setting-row"><div><p>{language==='no'?'Vis påminnelser når du åpner appen.':'Show reminders when you open the app.'}</p></div><Switch aria-label={language==='no'?'Midlertidige påminnelser':'Temporary reminders'} checked={notify} disabled={!auth} onCheckedChange={async v=>{try{await mutate({action:'notifications',enabled:v});setNotify(v);}catch(e:any){setError(e.message);}}}/></div>
      <p className="small muted">{language==='no'?'Varsler mens appen er lukket er ikke tilgjengelige i denne versjonen.':'Background notifications are not supported in this version.'}</p>
    </details>
    <details className="settings-card compact-settings">
      <summary>{language==='no'?'Data og personvern':'Data and privacy'}</summary>
      <p>{language==='no'?'Ingen annonser. Dataene dine selges ikke.':'No ads. Your data is never sold.'}</p>
      <button className="setting-action" onClick={exportData}><Download size={18}/>{language==='no'?'Eksporter minnene mine':'Export my memories'}<ChevronRight size={17}/></button>
      <button className="setting-action danger" disabled={!auth||!items.length} onClick={()=>setConfirm('clear')}><Trash2 size={18}/>{language==='no'?'Slett alle minner':'Delete all memories'}<ChevronRight size={17}/></button>
      <button className="setting-action danger" disabled={!auth} onClick={()=>setConfirm('account')}><Trash2 size={18}/>{language==='no'?'Slett appkonto':'Delete app account'}<ChevronRight size={17}/></button>
    </details>
    {error&&<div role="alert" className="error">{error}</div>}
  </section>}
 </main></div>
 <nav className="mobile-nav"><button className={view==='home'?'active':''} onClick={()=>{setView('home');setSearched(false);}}><Home size={22}/>{language==='no'?'Hjem':'Home'}</button><button className="mobile-add" onClick={()=>openAdd()}><Plus size={23}/>{language==='no'?'Husk':'Remember'}</button><button className={view==='settings'?'active':''} onClick={()=>setView('settings')}><Settings size={22}/>{language==='no'?'Innstillinger':'Settings'}</button></nav>
 {notice&&<div className="toast" role="status"><CheckCircle2 size={19}/>{notice}</div>}
 <Dialog open={!!modal} onOpenChange={v=>{if(!v){setModal('');recognitionRef.current?.abort();setError('');}}}><DialogContent className="memory-dialog"><DialogTitle>{modal==='add'?(language==='no'?'Hva skal jeg huske?':'What should I remember?'):modal==='edit'?(language==='no'?'Rediger minne':'Edit memory'):modal==='move'?(language==='no'?'Hvor ble det av?':'Where did it go?'):modal==='history'?(language==='no'?'Alle steder den har vært.':'Everywhere it has been.'):modal==='onboarding'?onboarding===1?'La tingene dine få en hukommelse.':onboarding===2?'Hva er det du alltid mister?':onboarding===3?`Where ${firstItem==='Keys'||firstItem==='Earbuds'||firstItem==='Chargers'?'are':'is'} your ${firstItem.toLowerCase()} akkurat nå?`:'Got it. I’ll remember that. 👌':selected?.name??'Your memory'}</DialogTitle><DialogDescription>{modal==='add'||modal==='move'||modal==='edit'?(language==='no'?'Kontroller detaljene før du lagrer.':'Review the details before saving.'):modal==='onboarding'?'Hjemmet ditt husker.':language==='no'?'Det er det siste stedet du fortalte meg.':'That’s the last place you told me.'}</DialogDescription>
 {modal==='move'&&(draft?confirmation:remembering)}
 {(modal==='add'||modal==='edit')&&<><div hidden={!!draft}><StructuredMemoryForm initial={modal==='edit'?selected||undefined:undefined} locations={locations} recentLocations={recentLocations} language={language} onPhoto={setPhoto} onCreateLocation={async value=>{const result=await mutate({action:'location_create',...value});await load();return result.id;}} onCreate={value=>{setDraft({...value,temporaryUntil:modal==='edit'?selected?.temporary_until||'':'',source:'manual edit'});setSource('manual edit');}}/></div>{draft&&confirmation}</>}
 {modal==='onboarding'&&(onboarding===1?<div className="onboard"><div className="welcome-symbol large"><Box size={50}/><MapPin size={28}/></div><h2>Hvor la jeg den?</h2><p>Litt mer ro i hverdagen.<br/>Én husket ting om gangen.</p><button className="primary full" onClick={()=>setOnboarding(2)}>Kom i gang</button></div>:onboarding===2?<div className="choices">{['Keys','Earbuds','Chargers','Noe annet'].map(n=><button className="secondary" key={n} onClick={()=>{setFirstItem(n==='Noe annet'?'item':n);setText('');setDraft(null);setOnboarding(3);}}><span>{emoji(n)}</span>{n}<ChevronRight size={18}/></button>)}</div>:onboarding===3?<>{draft?confirmation:<>{remembering}<div className="quick-locations"><span>Velg eventuelt et sted</span>{['Kjøkken → Skuff','Soverom → Skrivebord','Gang → Skap'].map(l=><button className="secondary" disabled={firstItem==='item'} key={l} onClick={()=>{setSource('manual edit');setDraft({name:firstItem==='item'?'Tingen min':firstItem,location:l.split(' → '),temporaryUntil:''});}}>{l}</button>)}</div></>}</>:<div className="onboard"><CheckCircle2 size={54} className="green"/><h2>{items[0]?.name}</h2><p>{items[0]?.location.join(' → ')}</p><button className="primary full" onClick={()=>{setModal('');setOnboarding(0);}}>{language==='no'?'Ferdig':'Done'}</button></div>)}
 {(modal==='detail'||modal==='history')&&selected&&<><div className="detail-summary"><span className="item-emoji big">{selected.icon||emoji(selected.name)}</span><div><small className="muted">{language==='no'?'Nåværende plassering':'Current location'}</small><h2>{selected.location.join(' → ')}</h2>{fixedAddress(selected.location)&&<a className="map-link" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(fixedAddress(selected.location)!)} target="_blank" rel="noreferrer">{language==='no'?'Vis adresse i kart':'View address on map'}</a>}{selected.temporary_until&&<p className="temporary"><Clock size={14}/>Midlertidig til {selected.temporary_until}</p>}</div></div>{typeof selected.saved_latitude==='number'&&typeof selected.saved_longitude==='number'&&<a className="map-link memory-map-link" href={'https://www.google.com/maps/search/?api=1&query='+selected.saved_latitude+','+selected.saved_longitude} target="_blank" rel="noreferrer"><MapPin size={15}/>{language==='no'?'Se lagringspin':'View saved pin'}</a>}{selected.photo&&<img className="item-photo" alt={selected.name} src={'/api/photo?key='+encodeURIComponent(selected.photo)}/>}{selected.description&&<p className="muted memory-description">{selected.description}</p>}{modal==='detail'?<><p className="muted">{language==='no'?'Sist husket':'Last saved'} {ago(selected.updated_at,language)}.</p><div className="button-row"><button className="primary" disabled={demo} onClick={()=>openAdd(selected)}>{language==='no'?'Flytt den':'Move it'} <MoveRight size={17}/></button><button className="secondary" disabled={demo} onClick={()=>openEdit(selected)}>{language==='no'?'Rediger':'Edit'}</button><button className="secondary" onClick={()=>setModal('history')}>{language==='no'?'Se historikk':'View history'}</button></div><button className="text-button danger" disabled={demo} onClick={()=>setConfirm('item')}><Trash2 size={15}/>{language==='no'?'Glem denne tingen':'Forget this item'}</button></>:<div className="timeline">{(selected.history.length?selected.history:[{location:selected.location,timestamp:selected.updated_at,source:'Example'}]).map((h,index)=><div className="timeline-row" key={index}><span className="timeline-dot"/><div><small>{title(ago(h.timestamp,language))}{index===0?(language==='no'?' · Nå':' · Current'):''}</small><h3>{h.location.join(' → ')}</h3><p>{h.source==='voice'?'Fortalt med stemmen':h.source==='Example'?'Eksempelminne':h.source==='manual edit'?(language==='no'?'Redigert av deg':'Edited by you'):'Skrevet av deg'}</p></div></div>)}</div>}</>}
 </DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm('');}}><AlertDialogContent className="memory-dialog"><AlertDialogTitle>{confirm==='item'?(language==='no'?'Glem denne tingen?':'Forget this item?'):confirm==='account'?(language==='no'?'Slette appkontoen?':'Delete your app account?'):(language==='no'?'Glemme alle minnene?':'Forget all your memories?')}</AlertDialogTitle><AlertDialogDescription>{language==='no'?('Dette sletter permanent '+(confirm==='item'?'tingen og historikken':confirm==='account'?'appkontoen, minner, historikk og bilder':'alle ting, historikk og bilder')+'. Handlingen kan ikke angres.'):('This permanently deletes '+(confirm==='item'?'this item and its history':confirm==='account'?'your app profile, memories, history and photos':'all your items, history and photos')+'. You cannot undo this.')}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>{language==='no'?'Avbryt':'Cancel'}</AlertDialogCancel><AlertDialogAction disabled={busy} className="delete-button" onClick={e=>{e.preventDefault();remove();}}>{busy?(language==='no'?'Sletter…':'Deleting…'):(language==='no'?'Slett permanent':'Delete permanently')}</AlertDialogAction></AlertDialogFooter>{error&&<p className="error">{error}</p>}</AlertDialogContent></AlertDialog>
 </div>;
}
