'use client';
import {useEffect,useRef,useState} from 'react';
import {Search,Mic,Plus,Home,Settings,MapPin,ChevronRight,ArrowUpRight,Clock,Check,ShieldCheck,Box,Camera,Trash2,Download,Headphones,Keyboard,MoveRight,X,CheckCircle2,Lock,HelpCircle} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Switch} from '@/components/ui/switch';
import {Memory,parseMemory,searchMemories,emoji,examples,title} from '@/lib/memory';
const placeholders=['Where are my keys?','Where did I put my passport?','Where’s my charger?','Where are my headphones?'];
function Brand({small=false}:{small?:boolean}){return <div className={'brand '+(small?'small':'')}><div className="brand-icon"><Box size={25}/><MapPin size={17}/></div><span>Where Did<br/>I Put That<span className="green">?</span></span></div>}
function ago(date:string){const days=Math.floor((Date.now()-new Date(date).getTime())/86400000);return days<1?'today':days===1?'yesterday':new Date(date).toLocaleDateString('en-US',{month:'short',day:'numeric'});}
export default function MemoryApp(){
 const [items,setItems]=useState<Memory[]>([]),[loaded,setLoaded]=useState(false),[demo,setDemo]=useState(false),[auth,setAuth]=useState(false),[email,setEmail]=useState(''),[query,setQuery]=useState(''),[searched,setSearched]=useState(false),[filter,setFilter]=useState('All memories'),[view,setView]=useState('home'),[modal,setModal]=useState(''),[selected,setSelected]=useState<Memory|null>(null),[text,setText]=useState(''),[draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[listening,setListening]=useState(false),[source,setSource]=useState('typed'),[onboarding,setOnboarding]=useState(0),[firstItem,setFirstItem]=useState('Keys'),[notify,setNotify]=useState(false),[confirm,setConfirm]=useState(''),[photo,setPhoto]=useState<File|null>(null),[placeIndex,setPlaceIndex]=useState(0);
 const inputRef=useRef<HTMLInputElement>(null);const recognitionRef=useRef<any>(null);
 async function load(){try{const r=await fetch('/api/memories');const d:any=await r.json();if(r.status===401){setAuth(false);setLoaded(true);return;}if(!r.ok)throw Error(d.error);setAuth(true);setEmail(d.user.email);setNotify(d.notifications==='on');const location=(id:string):string[]=>{const path:string[]=[];const visited=new Set();let current=id;while(current&&!visited.has(current)){visited.add(current);const l=d.locations.find((l:any)=>l.id===current);if(!l)break;path.unshift(l.name);current=l.parent_location_id;}return path;};setItems(d.items.map((i:any)=>({...i,location:location(i.current_location_id),history:d.history.filter((h:any)=>h.item_id===i.id).map((h:any)=>({...h,location:location(h.location_id)}))})));setLoaded(true);}catch(e:any){setError(e.message);setLoaded(true);}}
 useEffect(()=>{load();const t=setInterval(()=>setPlaceIndex(i=>(i+1)%4),4500);return()=>{clearInterval(t);recognitionRef.current?.abort();};},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t);},[notice]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const abort=new AbortController();Promise.resolve(ctx.registerTool({name:'search_memories',description:'Search your saved belongings and show all matching locations.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(p:any)=>{if(typeof p.query!=='string'||!p.query.trim())throw Error('A search query is required');setQuery(p.query);setSearched(true);setView('home');return searchMemories(items,p.query).map(i=>({name:i.name,location:i.location}));}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort();},[items]);
 const visible=demo?examples:items;const matches=searched?searchMemories(visible,query):[];const rooms=[...new Set(visible.map(i=>i.location[0]))];const shown=visible.filter(i=>filter==='All memories'||i.location[0]===filter);
 function openAdd(item?:Memory){setSelected(item??null);setText('');setDraft(null);setPhoto(null);setError('');setSource('typed');setModal(item?'move':'add');}
 function search(q=query){setQuery(q);setSearched(true);setView('home');setFilter('All memories');}
 function voice(target:'search'|'remember'){const API=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!API){setError('Voice isn’t supported in this browser. You can type your memory below.');return;}if(listening){recognitionRef.current?.stop();return;}const r=new API();recognitionRef.current=r;r.lang='en-US';r.interimResults=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=(e:any)=>{setListening(false);setError(e.error==='not-allowed'?'Please allow microphone access, or type instead.':'I didn’t catch that. Try again or type it.');};r.onresult=(e:any)=>{const result=e.results[0][0].transcript;if(target==='search')search(result);else{setText(result);setSource('voice');}setListening(false);};try{r.start();}catch{setError('Couldn’t start the microphone. Try typing instead.');}}
 function extract(){setError('');const d=parseMemory(text,modal==='move'?selected?.name:onboarding===3&&firstItem!=='item'?firstItem:undefined);if(!d){setError('Where should I look? Try “My keys are in the kitchen drawer.”');return;}setDraft(d);}
 async function mutate(payload:any){const r=await fetch('/api/memories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d:any=await r.json();if(!r.ok)throw Error(d.error||'That didn’t work. Please try again.');return d;}
 async function save(){if(!draft)return;if(!auth){setError('Sign in to keep this memory safe across visits.');return;}setBusy(true);setError('');try{let key;if(photo){const f=new FormData();f.append('photo',photo);const r=await fetch('/api/photo',{method:'POST',body:f});const d:any=await r.json();if(!r.ok)throw Error(d.error);key=d.key;}await mutate({...draft,id:modal==='move'?selected?.id:undefined,temporaryUntil:draft.temporaryUntil,source,photo:key});await load();setDemo(false);setSearched(false);setDraft(null);setText('');if(onboarding===3){setOnboarding(4);}else{setModal('');setNotice('Got it. I’ll remember that. 👌');}}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{await mutate({action:confirm==='item'?'delete':confirm,id:selected?.id});await load();setModal('');setSelected(null);setConfirm('');setNotice(confirm==='account'?'Your app account and memories have been deleted.':'Your memories have been deleted.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify(items,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='my-memories.json';a.click();URL.revokeObjectURL(url);}
 const remembering=<><button className={'voice-button '+(listening?'listening':'')} onClick={()=>voice('remember')}><Mic size={25}/>{listening?'I’m listening…':'Tell me'}</button><div className="or">or type it here</div><textarea value={text} onChange={e=>{setText(e.target.value);setSource('typed');}} placeholder={modal==='move'?'I moved it to my backpack.':'I put my passport in the top drawer in my bedroom.'} autoFocus/><div className="input-tip"><HelpCircle size={14}/>Just the item and its location. We’ll take it from there.</div>{error&&<div role="alert" className="error">{error}</div>}<button className="primary full" onClick={extract} disabled={!text.trim()}>Remembering starts here <Check size={17}/></button></>;
 const confirmation=draft&&<><div className="confirmation-card"><span className="item-emoji big">{emoji(draft.name)}</span><h2>{draft.name}</h2><p><MapPin size={16}/>{draft.location.join(' → ')}</p>{draft.temporaryUntil&&<small><Clock size={14}/>Temporary until {draft.temporaryUntil}</small>}</div><p className="center muted">Does that look right? I’ll remember exactly this.</p><label className="attach"><Camera size={18}/>{photo?photo.name:'Add a photo (optional)'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setPhoto(e.target.files?.[0]??null)}/></label>{!auth&&<a className="primary full" href="/signin-with-chatgpt?return_to=%2F" target="_top"><Lock size={16}/>Sign in to save</a>}{error&&<p role="alert" className="error">{error}</p>}<div className="button-row"><button className="secondary" onClick={()=>setDraft(null)}>Edit</button><button className="primary" disabled={busy||!auth} onClick={save}>{busy?'Remembering…':'Remember it'}<Check size={17}/></button></div></>;
 return <div className="app-shell"><aside className="sidebar"><Brand/><div className="nav-label">YOUR LITTLE MEMORY BANK</div><nav><button className={view==='home'?'active':''} onClick={()=>{setView('home');setSearched(false);}}><Home size={20}/>Home</button><button onClick={()=>openAdd()}><Plus size={20}/>Remember something</button><button className={view==='settings'?'active':''} onClick={()=>setView('settings')}><Settings size={20}/>Settings</button></nav><div className="sidebar-bottom"><div className="privacy-note"><ShieldCheck size={20}/><div>Just between us.<br/><span>Your memories stay yours.</span></div></div><button className="profile" onClick={()=>setView('settings')}><span className="avatar">{auth?email[0]?.toUpperCase():'Y'}</span><span>Your personal space<small>{auth?'Private & secure':'Make yourself at home'}</small></span><ChevronRight size={16}/></button></div></aside>
 <div className="main-wrap"><header className="topbar"><span className="breadcrumb"><Home size={15}/>Your home<span>/</span>{view==='home'?'Memory bank':'Settings'}</span><div className="topbar-right"><span><Lock size={13}/>Private by design</span><button className="avatar" aria-label="Open settings" onClick={()=>setView('settings')}>{auth?email[0]?.toUpperCase():'Y'}</button></div><div className="mobile-brand"><Brand small/></div></header>
 <main>{view==='home'?<><section className="intro"><div className="eyebrow"><span/>A LITTLE LESS “WHERE IS IT?”</div><h1>Your house<br className="mobile-break"/> remembers<span className="green">.</span></h1><p>You’ve got enough on your mind.<br className="mobile-break"/> Let us keep track of the little things.</p></section>
 <section className={'search-panel '+(searched?'expanded':'')}><form onSubmit={e=>{e.preventDefault();search();}}><Search size={25}/><div className="search-input"><label htmlFor="search">What are you looking for?</label><input id="search" ref={inputRef} value={query} onChange={e=>{setQuery(e.target.value);if(!e.target.value)setSearched(false);}} placeholder={placeholders[placeIndex]}/></div>{query&&<button type="button" className="icon-button clear" aria-label="Clear search" onClick={()=>{setQuery('');setSearched(false);}}><X size={17}/></button>}<button type="button" className={'mic '+(listening?'listening':'')} aria-label="Search by voice" onClick={()=>voice('search')}><Mic size={21}/></button><button className="search-submit" type="submit">Find it</button></form><div className="search-footer"><span><Mic size={13}/>{listening?'I’m listening…':'Ask naturally. Type it or say it.'}</span><span className="keyboard-hint"><Keyboard size={13}/>Enter to find</span></div></section>
 {error&&!modal&&<div role="alert" className="error">{error}<button onClick={()=>{setError('');load();}}>Try again</button></div>}
 {searched?<section className="result-section"><div className="section-head"><h2>{matches.length===1?'I found it. 👀':matches.length>1?`I remember ${matches.length===2?'two':matches.length} of those. 👀`:'Hmm… I don’t remember that one. 🤔'}</h2><button className="text-button" onClick={()=>{setSearched(false);setQuery('');}}>Back to memories</button></div>{matches.length>1&&<p className="muted">Which one are you looking for?</p>}{matches.length===0?<div className="unknown"><Box size={35}/><h3>Want to teach me?</h3><p>Tell me where it is, and I’ll remember for next time.</p><button className="primary" onClick={()=>openAdd()}>Remember it <Plus size={16}/></button><button className="text-button" onClick={()=>{setSearched(false);inputRef.current?.focus();}}>Try again</button></div>:<div className="results">{matches.map(i=><article className="result-card" key={i.id}><div className="result-top"><span className="item-emoji big">{emoji(i.name)}</span><span className="found-label"><CheckCircle2 size={15}/>Remembered</span></div><h2>{i.name}</h2><div className="result-location"><MapPin size={20}/>{i.location.join(' → ')}</div>{i.temporary_until&&<p className="temporary"><Clock size={15}/>Temporary until {i.temporary_until}</p>}<p className="muted">Last remembered {ago(i.updated_at)}.<br/>That’s the last place you told me. 👌</p><div className="button-row"><button className="primary" onClick={()=>{if(demo){setNotice('This is a sample. Save your first memory to make it yours.');return;}openAdd(i);}}>Move it <MoveRight size={17}/></button><button className="secondary" onClick={()=>{setSelected(i);setModal('history');}}>View history</button></div></article>)}</div>}</section>:<>
 {!items.length&&!demo&&loaded&&<section className="welcome-strip"><div className="welcome-symbol"><Box size={25}/></div><div><h3>Let’s give your stuff a memory.</h3><p>Start with the thing you’re always looking for.</p></div><button className="primary" onClick={()=>{setOnboarding(1);setModal('onboarding');setDraft(null);setError('');}}>Get started<Plus size={16}/></button></section>}
 <section className="memories"><div className="section-head"><div><h2>Recent memories <span className="count">{visible.length}</span></h2><p>The little things, right where you left them.</p></div><button className="text-button desktop-add" onClick={()=>openAdd()}><Plus size={17}/>Remember something</button></div><div className="filters">{['All memories',...rooms].map(f=><button key={f} className={f===filter?'selected':''} onClick={()=>setFilter(f)}>{f==='All memories'?<Box size={14}/>:<Home size={14}/>} {f}</button>)}</div>
 {demo&&<div className="demo-note">Sample memories, just to show you around.<button onClick={()=>{setDemo(false);setFilter('All memories');}}>Make it yours</button></div>}
 {!loaded?<div className="empty-card"><p>Opening your memory bank…</p></div>:shown.length?<div className="memory-grid">{shown.map(i=><button key={i.id} className="memory-card" onClick={()=>{setSelected(i);setModal('detail');}}><div className="card-top"><span className={'item-emoji '+(emoji(i.name)==='📕'?'peach':emoji(i.name)==='🎧'?'lavender':'')}>{emoji(i.name)}</span><ArrowUpRight size={18}/></div><h3>{i.name}</h3><div className="location"><MapPin size={14}/>{i.location.map((l,index)=><span key={index}>{index>0&&<ChevronRight size={12}/>} {l}</span>)}</div>{i.temporary_until&&<div className="temporary"><Clock size={12}/>Until {i.temporary_until}</div>}<div className="card-bottom"><span>Remembered {ago(i.updated_at)}</span><span className="remembered-dot"/></div></button>)}<button className="add-card" onClick={()=>openAdd()}><span><Plus size={24}/></span><h3>One less thing to forget.</h3><p>Remember something</p></button></div>:<div className="empty-card"><div className="empty-icon"><Box size={31}/></div><h3>Nothing here yet.</h3><p>Let’s give your stuff a better memory.</p><button className="primary" onClick={()=>openAdd()}><Plus size={17}/>Remember something</button><button className="text-button" onClick={()=>{setDemo(true);setFilter('All memories');}}>Take a look at some examples <ArrowUpRight size={15}/></button></div>}
 </section><section className="gentle-tip"><div className="tip-icon"><Mic size={20}/></div><div><h3>A thought. A sentence. Remembered.</h3><p>“I put my passport in the top drawer in my bedroom.”</p></div><button aria-label="Try remembering by voice" onClick={()=>{openAdd();setTimeout(()=>voice('remember'),200);}}><ArrowUpRight size={21}/></button></section></>}
 <footer><span><ShieldCheck size={14}/>Your stuff. Your memories. Always private.</span><span>Made for a little peace of mind.</span></footer>
 </>:<section className="settings"><div className="eyebrow">YOUR PERSONAL SPACE</div><h1>A few little settings.</h1><p className="muted">You’re in control of what we remember.</p><div className="settings-card"><h2>Account</h2><p>{auth?email:'Sign in to save your memories privately.'}</p>{auth?<a href="/signout-with-chatgpt?return_to=%2F" target="_top" className="secondary">Sign out</a>:<a href="/signin-with-chatgpt?return_to=%2F" target="_top" className="primary">Sign in with ChatGPT</a>}</div><div className="settings-card"><div className="setting-row"><div><h2>Temporary reminders</h2><p>Show reminders when you open the app.</p></div><Switch aria-label="Temporary reminders" checked={notify} disabled={!auth} onCheckedChange={async v=>{try{await mutate({action:'notifications',enabled:v});setNotify(v);}catch(e:any){setError(e.message);}}}/></div><p className="small muted">Notifications while the app is closed aren’t available in this version.</p>{notify&&items.filter(i=>i.temporary_until).map(i=><p key={i.id} className="temporary"><Clock size={15}/>{i.name}: {i.location.join(' → ')} until {i.temporary_until}</p>)}</div><div className="settings-card"><h2>Your data & privacy</h2><p>Your memories are private, stored securely, and protected in transit. No ads. No selling your data.</p><button className="setting-action" onClick={exportData}><Download size={18}/>Export my memories<ChevronRight size={17}/></button><button className="setting-action danger" disabled={!auth||!items.length} onClick={()=>setConfirm('clear')}><Trash2 size={18}/>Delete all memories<ChevronRight size={17}/></button><button className="setting-action danger" disabled={!auth} onClick={()=>setConfirm('account')}><Trash2 size={18}/>Delete app account<ChevronRight size={17}/></button><p className="small muted">Deleting your app account removes this app’s profile, photos and memories. Your ChatGPT account stays active.</p></div>{error&&<div role="alert" className="error">{error}</div>}</section>}
 </main></div>
 <nav className="mobile-nav"><button className={view==='home'?'active':''} onClick={()=>{setView('home');setSearched(false);}}><Home size={22}/>Home</button><button className="mobile-add" onClick={()=>openAdd()}><Plus size={23}/>Remember</button><button className={view==='settings'?'active':''} onClick={()=>setView('settings')}><Settings size={22}/>Settings</button></nav>
 {notice&&<div className="toast" role="status"><CheckCircle2 size={19}/>{notice}</div>}
 <Dialog open={!!modal} onOpenChange={v=>{if(!v){setModal('');recognitionRef.current?.abort();setError('');}}}><DialogContent className="memory-dialog"><DialogTitle>{modal==='add'?'What should I remember?':modal==='move'?'Where did it go?':modal==='history'?'Everywhere it’s been.':modal==='onboarding'?onboarding===1?'Let’s give your stuff a memory.':onboarding===2?'What’s something you always lose?':onboarding===3?`Where ${firstItem==='Keys'||firstItem==='Earbuds'||firstItem==='Chargers'?'are':'is'} your ${firstItem.toLowerCase()} right now?`:'Got it. I’ll remember that. 👌':selected?.name??'Your memory'}</DialogTitle><DialogDescription>{modal==='add'||modal==='move'?'Tell me naturally. You’ll check the details before I save them.':modal==='onboarding'?'Your house remembers.':'That’s the last place you told me.'}</DialogDescription>
 {(modal==='add'||modal==='move')&&(draft?confirmation:remembering)}
 {modal==='onboarding'&&(onboarding===1?<div className="onboard"><div className="welcome-symbol large"><Box size={50}/><MapPin size={28}/></div><h2>Where Did I Put That?</h2><p>A little peace of mind.<br/>One remembered thing at a time.</p><button className="primary full" onClick={()=>setOnboarding(2)}>Get started</button></div>:onboarding===2?<div className="choices">{['Keys','Earbuds','Chargers','Something else'].map(n=><button className="secondary" key={n} onClick={()=>{setFirstItem(n==='Something else'?'item':n);setText('');setDraft(null);setOnboarding(3);}}><span>{emoji(n)}</span>{n}<ChevronRight size={18}/></button>)}</div>:onboarding===3?<>{draft?confirmation:<>{remembering}<div className="quick-locations"><span>Or choose a location</span>{['Kitchen → Drawer','Bedroom → Desk','Hallway → Cabinet'].map(l=><button className="secondary" disabled={firstItem==='item'} key={l} onClick={()=>{setSource('manual edit');setDraft({name:firstItem==='item'?'My item':firstItem,location:l.split(' → '),temporaryUntil:''});}}>{l}</button>)}</div></>}</>:<div className="onboard"><CheckCircle2 size={54} className="green"/><h2>{items[0]?.name}</h2><p>{items[0]?.location.join(' → ')}</p><button className="primary full" onClick={()=>{setModal('');setOnboarding(0);}}>Done</button></div>)}
 {(modal==='detail'||modal==='history')&&selected&&<><div className="detail-summary"><span className="item-emoji big">{emoji(selected.name)}</span><div><small className="muted">Current location</small><h2>{selected.location.join(' → ')}</h2>{selected.temporary_until&&<p className="temporary"><Clock size={14}/>Temporary until {selected.temporary_until}</p>}</div></div>{selected.photo&&<img className="item-photo" alt={selected.name} src={'/api/photo?key='+encodeURIComponent(selected.photo)}/>}{modal==='detail'?<><p className="muted">Last remembered {ago(selected.updated_at)}.</p><div className="button-row"><button className="primary" disabled={demo} onClick={()=>openAdd(selected)}>Move it <MoveRight size={17}/></button><button className="secondary" onClick={()=>setModal('history')}>View history</button></div><button className="text-button danger" disabled={demo} onClick={()=>setConfirm('item')}><Trash2 size={15}/>Forget this item</button></>:<div className="timeline">{(selected.history.length?selected.history:[{location:selected.location,timestamp:selected.updated_at,source:'Example'}]).map((h,index)=><div className="timeline-row" key={index}><span className="timeline-dot"/><div><small>{title(ago(h.timestamp))}{index===0?' · Current':''}</small><h3>{h.location.join(' → ')}</h3><p>{h.source==='voice'?'Told by voice':h.source==='Example'?'Sample memory':h.source==='manual edit'?'Edited by you':'Typed by you'}</p></div></div>)}</div>}</>}
 </DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm('');}}><AlertDialogContent className="memory-dialog"><AlertDialogTitle>{confirm==='item'?'Forget this item?':confirm==='account'?'Delete your app account?':'Forget all your memories?'}</AlertDialogTitle><AlertDialogDescription>This permanently deletes {confirm==='item'?'this item and its history':confirm==='account'?'your app profile, memories, history and photos':'all your items, history and photos'}. You can’t undo this.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep them</AlertDialogCancel><AlertDialogAction disabled={busy} className="delete-button" onClick={e=>{e.preventDefault();remove();}}>{busy?'Deleting…':'Delete permanently'}</AlertDialogAction></AlertDialogFooter>{error&&<p className="error">{error}</p>}</AlertDialogContent></AlertDialog>
 </div>;
}
